# Generated by Django 3.2.7 on 2021-09-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileadmin',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media '),
        ),
    ]
