# Generated by Django 3.2.7 on 2021-09-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_fileadmin_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileadmin',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
